import numpy as np
from mini_gpt import text, chars, V, stoi, itos, counts

# 🔢 Training pairs: for every position, input = this char, target = next char
xs = np.array([stoi[c] for c in text[:-1]])
ys = np.array([stoi[c] for c in text[1:]])
N = len(xs)

# 🧠 The brain: one row of V numbers per character (starts random)
np.random.seed(42)
W = np.random.randn(V, V) * 0.01
lr = 50

for step in range(301):
    # 1) Guess: look up the row of each input char → scores for the next char
    logits = W[xs]
    logits = logits - logits.max(axis=1, keepdims=True)
    probs = np.exp(logits)
    probs /= probs.sum(axis=1, keepdims=True)
    loss = -np.mean(np.log(probs[np.arange(N), ys] + 1e-9))

    # 2) Error: guess − correct answer
    dlogits = probs.copy()
    dlogits[np.arange(N), ys] -= 1
    dlogits /= N

    # 3) Which rows of W caused the error?
    dW = np.zeros_like(W)
    np.add.at(dW, xs, dlogits)

    # 4) Fix the weights a little
    W -= lr * dW

    if step % 50 == 0:
        print(f"step {step:3d} | loss {loss:.3f}")

# 🔍 Did it learn the same thing as counting?
row = W[stoi["取"]]
print(f"\nAfter '取' → counting says '{itos[counts[stoi['取']].argmax()]}', network says '{itos[row.argmax()]}'")


def generate(max_len=30):
    out, current = "", "\n"
    for _ in range(max_len):
        z = W[stoi[current]]
        p = np.exp(z - z.max())
        p /= p.sum()
        nxt = itos[np.random.choice(V, p=p)]
        if nxt == "\n":
            break
        out += nxt
        current = nxt
    return out


print("\n🤖 Generated by the neural network:")
np.random.seed(0)
for _ in range(8):
    print("  ", generate())